/**
 * Internal tracking numbers.
 *
 * Every order carries one, generated by us at creation. It is the only
 * identifier a client ever sees, so it is deliberately *not* the sequential
 * `orderNo`: handing out `AS-2026-0148` tells the holder both how many orders
 * came before theirs and what to type to read someone else's.
 *
 * Format: `AS-YYYY-XXXXXX`, where the suffix is six symbols of a 32-character
 * alphabet with I, L, O and U removed — the glyph pairs that get misread when a
 * number is spelled out over WhatsApp or copied off a printed slip. 32^6 is
 * about 1.07 billion values, so guessing one is impractical.
 */

/** Crockford-style base 32: no I, L, O or U. */
export const TRACKING_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";

const SUFFIX_LENGTH = 6;

export const TRACKING_NUMBER_PATTERN = new RegExp(
  `^AS-\\d{4}-[${TRACKING_ALPHABET}]{${SUFFIX_LENGTH}}$`,
);

export function isValidTrackingNumber(value: string): boolean {
  return TRACKING_NUMBER_PATTERN.test(value);
}

/**
 * Build one tracking number.
 *
 * `random` is injected so the seed generator can pass its own deterministic
 * source and keep the mock dataset stable between reloads.
 */
export function generateTrackingNumber(
  year: number,
  random: () => number = Math.random,
): string {
  let suffix = "";
  for (let i = 0; i < SUFFIX_LENGTH; i += 1) {
    suffix += TRACKING_ALPHABET[Math.floor(random() * TRACKING_ALPHABET.length)];
  }
  return `AS-${year}-${suffix}`;
}

/**
 * Build a tracking number that is not already in `taken`.
 *
 * Uniqueness has no database to lean on yet (see SPEC.md §2.2), so this is a
 * best-effort check against the records we can see. It is not a guarantee.
 */
export function generateUniqueTrackingNumber(
  year: number,
  taken: Iterable<string>,
  random: () => number = Math.random,
): string {
  const used = new Set(taken);
  for (let attempt = 0; attempt < 50; attempt += 1) {
    const candidate = generateTrackingNumber(year, random);
    if (!used.has(candidate)) return candidate;
  }
  throw new Error("could not generate an unused tracking number");
}
